extends: 'eslint:recommended'
env:
  browser: true
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - code: 100
      tabWidth: 2
      ignoreUrls: true
  quotes:
    - warn
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  no-multi-spaces:
    - error
  keyword-spacing:
    - warn
    - overrides:
        catch:
          after: false
  brace-style:
    - error
  space-before-function-paren:
    - warn
    - never
  function-paren-newline:
    - warn
    - consistent
  space-before-blocks:
    - warn
    - always
  block-spacing:
    - warn
    - always
  key-spacing:
    - warn
  object-curly-spacing:
    - warn
    - always
  space-infix-ops:
    - warn
  space-in-parens:
    - warn
  no-unused-vars:
    - warn
  no-console:
    - warn
    - allow:
      - error
      - warn
  no-var:
    - error
  arrow-body-style:
    - warn
  arrow-parens:
    - warn
    - as-needed
  arrow-spacing:
    - warn

overrides:
  - files:
      - "*.config.js"
    env:
      browser: false
      node: true
      es6: true
    parserOptions:
      sourceType: module
