extends: stylelint-config-standard
ignorePath: .gitignore

plugins:
  - stylelint-no-unsupported-browser-features

rules:
  indentation:
    - tab

  max-line-length:
    - 100
    - ignorePattern: /// https?:///

  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - at-root
        - mixin
        - include
        - extend
        - function
        - return
        - each
        - if
        - else
        - content

  at-rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - blockless-after-same-name-blockless
      ignoreAtRules:
        - else

  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
        - if
        - else

  declaration-colon-newline-after: null

  function-comma-newline-after: null

  declaration-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - after-declaration

  declaration-block-no-redundant-longhand-properties:
    - true
    - severity: warning

  declaration-colon-space-after:
    - always-single-line

  ## This selectors could not be sorted by specificity:
  # .scrollable { // 0-1-0
  #   table {} // 0-1-1
  # }
  #
  # a + .scrollable, // 0-1-1
  # a + table { // 0-0-2
  # }
  ## Specifity specification: https://www.w3.org/TR/selectors-3/#specificity
  no-descending-specificity: null

  ## https://github.com/stylelint/stylelint/issues/4622
  value-keyword-case:
    - lower
    - ignoreKeywords:
      - BlinkMacSystemFont

  plugin/no-unsupported-browser-features:
    - true
    - severity: warning
      ignore:
        - flexbox
        - css3-cursors
        ## https://github.com/anandthakker/doiuse/issues/70
        - outline
        ## Let's reconcile with IE 11
        - css-appearance
